language: php

sudo: required

language: php

dist: trusty

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  apt:
    packages:
      - default-jdk
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - g++

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1.30
 - 7.2
 
env:
 global:
  - MOODLE_BRANCH=MOODLE_35_STABLE
  - MOODLE_BRANCH=MOODLE_36_STABLE
  - MOODLE_BRANCH=MOODLE_37_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - >
    if [ "$DB" = 'mysqli' ];
    then
        moodle-plugin-ci install
        sudo mkdir /mnt/ramdisk
        sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
        sudo stop mysql
        sudo mv /var/lib/mysql /mnt/ramdisk
        sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
        sudo start mysql
    fi
  - >
    if [ "$DB" = 'pgsql' ];
    then
        moodle-plugin-ci install
        sudo mkdir /mnt/ramdisk
        sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
        sudo service postgresql stop
        sudo mv /var/lib/postgresql /mnt/ramdisk
        sudo ln -s /mnt/ramdisk/postgresql /var/lib/postgresql
        sudo service postgresql start 9.6
    fi

before_script:
  - chmod +x /home/travis/build/moodle/mod/vpl/tests/vpl_evaluate/test_vpl_evaluate.sh

script:
  - moodle-plugin-ci phplint
#  CPD errors I need to rewrite scala and python tokenizer
#  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
  - /home/travis/build/moodle/mod/vpl/tests/vpl_evaluate/test_vpl_evaluate.sh
  
  